---
- name: install docker-py workaround
  sudo: yes
  pip: name=docker-py version=1.7.0

- name: start redis container
  docker:
    name: "{{ container_name }}"
    image: redis
    state: reloaded
    ports:
      - "6379:6379"
